<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PagoMoviles.Abstract\PagoMoviles.Abstract.csproj" />
    <ProjectReference Include="..\PagoMoviles.DataAccess\PagoMoviles.DataAccess.csproj" />
    <ProjectReference Include="..\PagoMoviles.Entities\PagoMoviles.Entities.csproj" />
  </ItemGroup>

</Project>
