//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosMovilesWeb.Portal
{
    public partial class PTL6_Desinscripcion
    {
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTelefono;
        protected global::System.Web.UI.WebControls.TextBox txtCuenta;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCuenta;
        protected global::System.Web.UI.WebControls.Button btnDesinscribir;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlExito;
        protected global::System.Web.UI.WebControls.Label lblExito;
    }
}
