//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosMovilesWeb.Portal
{
    public partial class PTL8_UltimosMovimientos
    {
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTelefono;
        protected global::System.Web.UI.WebControls.Button btnConsultar;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlResultados;
        protected global::System.Web.UI.WebControls.Label lblNumeroCuenta;
        protected global::System.Web.UI.WebControls.Label lblTelefono;
        protected global::System.Web.UI.WebControls.GridView gvMovimientos;
    }
}
