//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosMovilesWeb.Admin
{
    public partial class SA12_ReporteTransacciones
    {
        protected global::System.Web.UI.WebControls.TextBox txtFecha;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFecha;
        protected global::System.Web.UI.WebControls.Button btnConsultar;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlResultados;
        protected global::System.Web.UI.WebControls.Label lblFechaConsultada;
        protected global::System.Web.UI.WebControls.GridView gvTransacciones;
        protected global::System.Web.UI.WebControls.Label lblTotalDia;
    }
}
