//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosMovilesWeb.MasterPages
{
    public partial class Admin
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkInicio;
        protected global::System.Web.UI.WebControls.HyperLink lnkUsuarios;
        protected global::System.Web.UI.WebControls.HyperLink lnkClientes;
        protected global::System.Web.UI.WebControls.HyperLink lnkCuentas;
        protected global::System.Web.UI.WebControls.HyperLink lnkReporte;
        protected global::System.Web.UI.WebControls.HyperLink lnkRoles;
        protected global::System.Web.UI.WebControls.HyperLink lnkPantallas;
        protected global::System.Web.UI.WebControls.LinkButton lnkLogout;
        protected global::System.Web.UI.WebControls.Label lblUsuario;
    }
}
