//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosMovilesWeb.MasterPages
{
    public partial class Portal
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkInicio;
        protected global::System.Web.UI.WebControls.HyperLink lnkDesinscribir;
        protected global::System.Web.UI.WebControls.HyperLink lnkSaldo;
        protected global::System.Web.UI.WebControls.HyperLink lnkMovimientos;
        protected global::System.Web.UI.WebControls.HyperLink lnkTransferir;
        protected global::System.Web.UI.WebControls.LinkButton lnkLogout;
        protected global::System.Web.UI.WebControls.Label lblUsuarioPortal;
    }
}